* nodos distinguidos 

** red casa-eric
Utilizando el modelo que toma cada ip (ya sea fuente o destino) como
un símbolo distinto, vemos que el la red casa-eric tenemos un alfabeto
compuesto de 255 símbolos: los IPs del 192.168.0.1 a 192.168.0.254 y
la IP 0.0.0.0.

La entropía en el muestreo realizado en esa red dió un valor de
5.010991. Si comparamos la información de cada symbolo (estimando su
probabilidad de ocurrencia con la frecuencia empírica obtenida en la
muestra) con la entropía de la fuente calculada también con la
muestra, obeservamos que existe un único nodo distinguido, a saber el
nodo con el número 192.168.0.1, el cual tiene una frecuencia mucho
mayor y por ende una cantidad de información menor: es el único
símbolo que transmite uan información menor a la entropía de la
fuente. Este echo no es casual, ya que ese es el IP correspondiente al
default gateway (de acuerdo al comando ip route corrido en la
computadora donde se realizó el muestreo), y probablemnte sea por lo
tanto el router de la red.

En el grafo puede verse que este nodo tiene muchas aristas que lo
conectan con muchos de los otros nodos de la red, la gran mayoría de
los cuales solo recibe un paquete del mismo.

[eric-lavarropas]

Al ver este grafo pensamos en considerar sólo aquellos nodos son tanto
fuente como detino de algún paque (es decir sin considerar aquellos
paquetes que el router envía a nodos que no envían ningún paquete).

[eric-flor]


** red biblio
La segunda red observada es la denominada "biblio". Utilizando el
modelo S2 en esta muestra obtuvimos un alfabeto de 178 símbolos. Estos
son, el IP 0.0.0.0, el 10.128.128.128, el 10.5.47.7, 98 que empiezan
con 10.92, 74 con 100.64 y por último los IPs 169.254.193.173 y
169.254.216.44. Los IPs que empiezan con 10.96 en realidad pertencen
al rango 10.96.0.* a 10.96.15.*, con lo que puede que pertenezcan a la
red 10.92.0.0/20. Las IPs que comienzan con 100.64 están en el rango
de 100.64.0.* a 100.64.31.* por lo que probablemente pertenezcan a la
red 100.64.0.0/19.

La entropía encontrada en esta fuente de información es de 3.569424,
lo que da lugar a que existen tres nodos distinguidos (considerando a
aquellos cuya información es menor), a saber, los nodos
10.128.128.128, 100.64.22.24 y 100.64.0.1.

Dado que observando los números de IP supusimos que existían dos
subredes, quisimos observar los vínculos entre los distintos nodos
para ver el grafo subyascente. Es decir, graficamos el grafo que está
compuesto por aquellas aristas que conectan dos nodos de distinta red,
lo cual se ve a continuación:

[biblio-grafo-redesAB.png]

Puede verse en este grafo qeu los dos nodos distinuidos de mayor
ocurrencia están presentes: el 10.128.128.128 y el 100.64.22.24, los
cuales están conectados mediante dos aristas con orientaciones
diferentes (o sea cada uno envió algún paquete al otro). Por otra
parte, todos los demás nodos pertenecen a 100.64.0.0/19 y reciben
paquetes de 10.128.128.128 (son paquetes who-has).

Luego dibujamos otros dos grafos. El primero de ellos es el de la red
biblio, pero sin los nodos pertenecientes a 10.128.

[biblio-grafo-red-100.64..png]

En el centro se ve el nodo distinguido 100.64.0.1, que suponemos puede
ser un router dado que tiene aristas que los conectan con una gran
cantidad de otros nodos de la red. 

Por último, el grafo correpondiente a las aristas entre nodos no
pertenecientes a 10.128.

[biblio-grafo-red-10.128.png]


** red pabellón 1
En esta red encontramos 209 símbolos, la mayoría de los cuales son IPs
que comienzan con 10.2.200 a 10.2.203, y también hay IPs que comienzan
con 169.254. De manera similar a la red biblio, hicimos el grafo de
los nodos con aristas que conectan ambas redes.

[exactas redesAB]

Vemos de la red 169.254 que el nodo 169.254.119 recibe muchos
paquetes. Cabe destacar que si bien la información de dicho IP resulta
mayor al valor de entropía de la red (es decir que no es tan
frecuente), es el de mayor frecuencia entre las direcciones 169.254.

En el grafo en el cual le sacamos los nodos de 10.2, podemos ver que
en su mayoría se trata de paquetes que van a 0.0.0.0.

[exactas sin 10.2]
Por último, el grafo de la red pabellón 1 al que le sacamos los nodos
cd 169.254 está compuesto de una gran cantidad de nodos, destacándose
el lugar del nodo destacado 10.2.203.254, que es el de mayor
frecuencia.

[xactas sin 169]
